package UI;
import CONTROLLER.RapportVisiteController;
/**
 *
 * @author Dan
 */
public class RapportVisiteUI extends javax.swing.JFrame{
    /**
     * Creates new form Rapport
     */
    public RapportVisiteUI() {
        initComponents();
        new RapportVisiteController().tabEchantillon();
        new RapportVisiteController().infoRap();
        this.Bilan.setLineWrap(true);
        this.Bilan.setWrapStyleWord(true);
        calendrier.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendrier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroRapport = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listPraticiens = new javax.swing.JComboBox();
        detail = new javax.swing.JButton();
        dateRapport = new javax.swing.JTextField();
        motifVisite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bilan = new javax.swing.JTextArea();
        suivant = new javax.swing.JButton();
        precedent = new javax.swing.JButton();
        nouveau = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fermer = new javax.swing.JButton();
        enregistrer = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        echantillons = new javax.swing.JTable();
        erreurRap = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(calendrier);
        calendrier.setBounds(410, 50, 120, 90);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Numéro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 25);

        numeroRapport.setEditable(false);
        numeroRapport.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numeroRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroRapportActionPerformed(evt);
            }
        });
        getContentPane().add(numeroRapport);
        numeroRapport.setBounds(121, 29, 75, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Praticien");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 70, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 90, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Motif");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 80, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Bilan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 80, 25);

        listPraticiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPraticiensActionPerformed(evt);
            }
        });
        getContentPane().add(listPraticiens);
        listPraticiens.setBounds(121, 58, 150, 25);

        detail.setText("Détails");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        getContentPane().add(detail);
        detail.setBounds(300, 60, 75, 25);

        dateRapport.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dateRapport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateRapportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateRapportFocusLost(evt);
            }
        });
        getContentPane().add(dateRapport);
        dateRapport.setBounds(121, 86, 75, 25);

        motifVisite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifVisiteActionPerformed(evt);
            }
        });
        getContentPane().add(motifVisite);
        motifVisite.setBounds(121, 112, 150, 25);

        Bilan.setColumns(10);
        Bilan.setRows(5);
        jScrollPane1.setViewportView(Bilan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 170, 200, 130);

        suivant.setText("Suivant");
        suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivantActionPerformed(evt);
            }
        });
        getContentPane().add(suivant);
        suivant.setBounds(170, 340, 100, 25);

        precedent.setText("Précédent");
        precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedentActionPerformed(evt);
            }
        });
        getContentPane().add(precedent);
        precedent.setBounds(60, 340, 100, 25);

        nouveau.setText("Nouveau");
        nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauActionPerformed(evt);
            }
        });
        getContentPane().add(nouveau);
        nouveau.setBounds(280, 340, 100, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Offres d'échantillons");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 170, 130, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 3, 238));
        jLabel7.setText("RAPPORTS DE VISITE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 10, 170, 17);

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });
        getContentPane().add(fermer);
        fermer.setBounds(540, 340, 100, 25);

        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(enregistrer);
        enregistrer.setBounds(410, 340, 110, 25);

        echantillons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        echantillons.setToolTipText("");
        echantillons.setCellSelectionEnabled(true);
        echantillons.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        echantillons.setFillsViewportHeight(true);
        jScrollPane4.setViewportView(echantillons);
        echantillons.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(350, 190, 210, 110);

        erreurRap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        erreurRap.setForeground(new java.awt.Color(204, 0, 0));
        erreurRap.setText(" ");
        getContentPane().add(erreurRap);
        erreurRap.setBounds(210, 30, 450, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/logo4.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-50, -10, 730, 450);

        setSize(new java.awt.Dimension(683, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void motifVisiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifVisiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motifVisiteActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_fermerActionPerformed

    private void listPraticiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPraticiensActionPerformed
        
    }//GEN-LAST:event_listPraticiensActionPerformed

    private void numeroRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroRapportActionPerformed

    }//GEN-LAST:event_numeroRapportActionPerformed

    private void nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauActionPerformed
        new RapportVisiteController().rapNouveau();
    }//GEN-LAST:event_nouveauActionPerformed

    private void suivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivantActionPerformed
        new RapportVisiteController().rapSuivant();
    }//GEN-LAST:event_suivantActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        new PraticienUI(listPraticiens.getSelectedIndex()).setVisible(true);
    }//GEN-LAST:event_detailActionPerformed

    private void dateRapportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateRapportFocusGained
        calendrier.setVisible(true);
    }//GEN-LAST:event_dateRapportFocusGained

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        new RapportVisiteController().rapEnregistrer();
    }//GEN-LAST:event_enregistrerActionPerformed

    private void precedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedentActionPerformed
        new RapportVisiteController().rapPrecedent();
    }//GEN-LAST:event_precedentActionPerformed

    private void dateRapportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateRapportFocusLost
        calendrier.setVisible(false);
    }//GEN-LAST:event_dateRapportFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RapportVisiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RapportVisiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RapportVisiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RapportVisiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RapportVisiteUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Bilan;
    public static javax.swing.JPanel calendrier;
    public static javax.swing.JTextField dateRapport;
    public static javax.swing.JButton detail;
    public static javax.swing.JTable echantillons;
    public static javax.swing.JButton enregistrer;
    public static javax.swing.JLabel erreurRap;
    public static javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JComboBox listPraticiens;
    public static javax.swing.JTextField motifVisite;
    public static javax.swing.JButton nouveau;
    public static javax.swing.JTextField numeroRapport;
    public static javax.swing.JButton precedent;
    public static javax.swing.JButton suivant;
    // End of variables declaration//GEN-END:variables

}